---
title: "MB5370 Module 04. Assignment: End-to-end data analysis in R"
author: "Nicole Welch"
output: html_document
date: "2024-05-16"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Install and load tidyverse packages
```{r}
## install.packages("tidyverse") # Delete this line once installed
library("tidyverse")
```

#read in data
```{r read data}
data <- read.delim("../data/Exercise2_Module04.txt")
data

str(data)

```

# Setting facotrs
```{r factors}
data$Area <- factor(data$Area)
data$Year <- factor(data$Year)
data$Species <- factor(data$Species)

```

``` {r data}
Species <- data |>
  group_by(Year, Species) |>
  summarize(avg_species = mean(count), 
           SE = sd(count)/sqrt(length(count)) )

```

```{r plot}
Plot <- 
  ggplot(Species, aes(Year, y = avg_species, color = Species)) +
  geom_pointrange(aes(ymin = avg_species-SE, ymax = avg_species+SE))+
  scale_color_manual(values = c("blue", "forestgreen"))+
  xlab("Year") +
  ylab("Average Species")+
  facet_wrap(~ Species,, scales = "free_y")

ggsave(filename = "../output/FinalPlot.jpg", plot = Plot)

# can create insets
# Turtles are significantly lower caught in drum lines 
# slight similarities in the variance 

```

scale = freey, varability in time 
