---
title: "MB5370 Module 04. Workshop 2 - Using ggplot2 for communication"
author: "Nicole Welch"
output: html_document
date: "2024-03-22"
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Labeling
```{r labeling}
# Good labels on plots can help you communicate your key findings, or even comply with the formatting requirements of any outlet (like a scientific journal or your company’s preferred style).

# Title:
ggplot(mpg, aes(displ, hwy)) +
  geom_point(aes(color = class)) +
  geom_smooth(se.e = FALSE) +
  labs(title = "Fuel efficiency generally decreases with engine size")

# Subtitle & Caption
ggplot(mpg, aes(displ, hwy)) +
  geom_point(aes(color = class)) +
  geom_smooth(se = FALSE) +
  labs(
    title = "Fuel efficiency generally decreases with engine size",
    subtitle = "Two seaters (sports cars) are an exception because of their light weight",
    caption = "Data from fueleconomy.gov"
  )

# replace axis labels and legend titles 
ggplot(mpg, aes(displ, hwy)) +
  geom_point(aes(colour = classs)) +
  geom_smooth(se = FALSE) +
  labs(
    x = "Engine displacement (L)",
    y = "Highway fuel economy (mpg)",
    colour = "Car type"
  )
```

# Annotations
``` {r Annotations}
best_in_class <- mpg %>%
  group_by(class) %>%
  filter(row_number(desc(hwy)) == 1)

ggplot(mpg, aes(displ, hwy)) +
  geom_point(aes(colour = class)) +
  geom_text(aes(label = model), data = best_in_class)
```
# Scales
```{r scales}
ggplot(mpg, aes(displ, hwy)) +
  geom_point(aes(colour = class))

# Remember that to provide limits you’ll need to offer a character vector showing the start and end of your limit (e.g. c(0,12)). Note also that: ?scale_x_continuous() has plenty of other arguments, so don’t forget to explicitly state the argument you’re providing these limits for (e.g. limits = c(0,12)). 
ggplot(mpg, aes(displ, hwy)) +
  geom_point(aes(colour = class)) +
  scale_x_continuous() +
  scale_y_continuous() +
  scale_colour_discrete()
```

# legends
```{ r legends and color scemes}
base <- ggplot(mpg, aes(displ, hwy)) +
  geom_point(aes(colour = class))

base + theme(legend.position = "left")
base + theme(legend.position = "top")
base + theme(legend.position = "bottom")
base + theme(legend.position = "right") # the default

```

# Replacing a scale
``` {r scaling}
ggplot(diamonds, aes(carat, price)) +
  geom_bin2d() + 
  scale_x_log10() + 
  scale_y_log10()

# Another scale that is frequently customised is the colour scale. In fact, from a data visualisation point of view, this is among the most important changes you can make to a base ggplot.

ggplot(mpg, aes(displ, hwy)) +
  geom_point(aes(color = drv))

ggplot(mpg, aes(displ, hwy)) +
  geom_point(aes(color = drv)) +
  scale_colour_brewer(palette = "Set1")

ggplot(mpg, aes(displ, hwy)) +
  geom_point(aes(color = drv, shape = drv)) +
  scale_colour_brewer(palette = "Set1")

# When you have predefined colours you want to use you can set them yourself, using scale_colour_manual()

presidential %>%
  mutate(id = 33 + row_number()) %>%
  ggplot(aes(start, id, colour = party)) +
    geom_point() +
    geom_segment(aes(xend = end, yend = id)) +
    scale_colour_manual(values = c(Republican = "red", Democratic = "blue"))

```

# Themes
```{r themes}

ggplot(mpg, aes(displ, hwy)) +
  geom_point(aes(color = class)) +
  geom_smooth(se = FALSE) +
  theme_bw()


ggplot(mpg, aes(displ, hwy)) +
  geom_point(aes(color = class)) +
  geom_smooth(se = FALSE) +
  theme_light()

# the better one
ggplot(mpg, aes(displ, hwy)) +
  geom_point(aes(color = class)) +
  geom_smooth(se = FALSE) +
  theme_classic()


ggplot(mpg, aes(displ, hwy)) +
  geom_point(aes(color = class)) +
  geom_smooth(se = FALSE) +
  theme_dark()
```




